### ISSUE TITLE
6/9/16 Reading Go Documentation and Web Development with G

### ISSUE THREAD

**Issue by GoesToEleven** [remotemeetup/go#3]
## Event
Title:
Reading Go Documentation and Web Development with Go

Date: 
6/9/16

Time (include time zone): 
6 PM PST

Duration:
1 hour

Description:
Reading documentation is important. Many new Go programmers struggle with reading documentation. There are a few key insights which, once you understand them, make reading documentation much easier. In addition, once you know how to read documentation properly, a world of programming power is opened up to you. In addition to gaining insights into reading documentation, I will also present the foundations of web programming with Go. Attendees will be given free access to valuable code repositories which will provide them with many code samples for both learning Go and learning Web Programming with Go.

List any pre-requisites:
A brain. A computer. A passion to learn.

Limit number of attendees to (our plan allows up to 100):
100

What type is your event (pick one that sounds more like it):

- [ ] Webinar
- [ ] Class/Tutorial
- [X] Presentation
- [ ] Demo

## Presenter(s)

All presenter(s) subscribed to our Remote Meetup Go channel?
- [X] yes

Enter below the name of each presenter so we can find them on the channel:
Todd McLeod

## Moderator(s)

We recommend that you have 1-4 moderators with some knowledge on the topic so they can help with the chat Q&A during the session. Keep in mind also that you will have the ability to choose to turn off the Q&A during your presentation and open it at the end.

All moderator(s) subscribed to our Remote Meetup Go channel?

- [X] yes

Enter the name of each moderator below so we can find them on the channel:
Gunjan Patel

**Comment by carlisia** [comment]
Event added. Thank you for this!
